Updated GhostScript version to 10.04.0

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,50 +1,69 @@
 #!/bin/bash
-# bin/compile <build-dir> <cache-dir>
-
-set -e
-
-BUILD_DIR=$1
 
 indent() {
   sed -u 's/^/       /'
 }
 
-arrow() {
-  sed -u 's/^/-----> /'
-}
+echo "-----> Install GhostScript"
 
-GS_VERSION_SEMVER="9.55.0"
-GS_VERSION="9550"
-echo "Installing Ghostscript $GS_VERSION_SEMVER using build directory $1" | arrow
+BUILD_DIR=$1
+CACHE_DIR=$2
+VENDOR_DIR="$BUILD_DIR/vendor"
+INSTALL_DIR="$VENDOR_DIR/ghostscript"
+GS_VERSION="10.04.0"
+GS_VERSION_SHORT="10040"
+CACHE_FILE="$CACHE_DIR/ghostscript-$GS_VERSION.tar.gz"
 
-PACKAGE="https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs$GS_VERSION/ghostscript-$GS_VERSION_SEMVER-linux-x86_64.tgz"
+if [ ! -f $CACHE_FILE ]; then
+  # install imagemagick
+  GS_FILE="ghostscript-$GS_VERSION.tar.xz"
+  GS_DIR="ghostscript-$GS_VERSION"
+  GS_URL="https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs$GS_VERSION_SHORT/$GS_FILE"
 
-GS_VENDOR="$BUILD_DIR/vendor/ghostscript"
-rm -rf $GS_VENDOR/*
-mkdir -p $GS_VENDOR/bin
+  echo "-----> Downloading GhostScript from $GS_URL"
+  wget $GS_URL -P $BUILD_DIR | indent
 
-GS_SOURCE_DIR="$GS_VENDOR/ghostscript-$GS_VERSION_SEMVER"
-rm -rf $GS_SOURCE_DIR
-mkdir -p $GS_SOURCE_DIR
+  echo "-----> Extracting GhostScript from $BUILD_DIR/$GS_FILE"
+  if [ ! -f $BUILD_DIR/$GS_FILE ]; then
+    echo "Error: Unable to download GhostScript" | indent
+    ls $BUILD_DIR | indent
+    exit 1;
+  fi
+  tar xvf $BUILD_DIR/$GS_FILE | indent
 
-echo "Fetching ghostscript binaries" | indent
-curl $PACKAGE -L -o - | tar xzf - -C $GS_SOURCE_DIR 2>&1 | indent
+  echo "-----> Building GhostScript"
+  cd $GS_DIR
+  export CPPFLAGS="-I$INSTALL_DIR/include"
+  export LDFLAGS="-L$INSTALL_DIR/lib"
+  ./configure --prefix=$INSTALL_DIR
+  make && make install
+  cd ..
+  rm -rf $GS_DIR
 
-# Extracted binary lives here
-GS_SOURCE_BINARY="$GS_SOURCE_DIR/ghostscript-$GS_VERSION_SEMVER-linux-x86_64/gs-$GS_VERSION-linux-x86_64"
-mv $GS_SOURCE_BINARY $GS_VENDOR/bin/gs
+  # cache for future deploys
+  echo "-----> Caching GhostScript installation"
+  cd $VENDOR_DIR
+  REL_INSTALL_DIR="ghostscript"
+  tar czf $REL_INSTALL_DIR.tar.gz $REL_INSTALL_DIR
 
-# Don't keep anything around
-rm -rf $GS_SOURCE_DIR
+  if [ ! -d $CACHE_DIR ]; then
+    mkdir -p $CACHE_DIR
+  fi
 
-mkdir -p $BUILD_DIR/bin
+  mv $REL_INSTALL_DIR.tar.gz $CACHE_FILE
 
-echo "Setting up ghostscript environment" | indent
-cp -R $GS_VENDOR/bin/* $BUILD_DIR/bin/
+else
+  # cache exists, extract it
+  echo "-----> Extracting GhostScript $CACHE_FILE => $VENDOR_DIR"
+  mkdir -p $VENDOR_DIR
+  tar xzf $CACHE_FILE -C $VENDOR_DIR
+fi
 
-mkdir -p $BUILD_DIR/.profile.d
-echo 'export PATH="$HOME/bin:$PATH"' > $BUILD_DIR/.profile.d/ghostscript.sh
-
-cat <<EOF > export
-export PATH=$BUILD_DIR/bin:$PATH
-EOF
+# update PATH and LD_LIBRARY_PATH
+echo "-----> Updating environment variables"
+PROFILE_PATH="$BUILD_DIR/.profile.d/ghostscript.sh"
+ACTUAL_INSTALL_PATH="$HOME/vendor/ghostscript"
+mkdir -p $(dirname $PROFILE_PATH)
+echo "export PATH=$ACTUAL_INSTALL_PATH/bin:\$PATH" >> $PROFILE_PATH
+echo "export MAGICK_CONFIGURE_PATH=$ACTUAL_INSTALL_PATH" >> $PROFILE_PATH
+echo "-----> Done updating environment variables. All set for GhostScript."
